### ISSUE TITLE
compilation err

### ISSUE THREAD

**Issue by Jacknq** [atifaziz/t5#5]
Hi, thanks for your project. 
When I try
```
<#@ template debug="true" hostspecific="true" language="C#" #>
<#@ import namespace="Newtonsoft.Json" #>
<#@ import namespace="System.Collections.Generic" #>
<#@ import namespace="System" #>
<#@ import namespace="System.IO" #>
<#@ import namespace="System.Linq" #>
<#@ import namespace="Microsoft.AspNetCore.Http" #>
<#@ import namespace="Microsoft.AspNetCore.Mvc" #>
<#@ import namespace="Microsoft.AspNetCore.Mvc.ApiExplorer" #>
<#@ import namespace="System.Reflection" #>
<#@ import namespace="Microsoft.AspNetCore.Mvc" #>
<#@ import namespace="System.Text.RegularExpressions" #>
<#@ import namespace="System.Threading.Tasks" #>
<#@ import namespace="System.Reflection" #>
<#@ import namespace="System.Runtime" #>
<#@ import namespace="System.Xml" #>
<#@ import namespace="System.Xml.Linq" #>
<#@ Assembly name="EnvDTE" #>
<#@ Assembly name="Microsoft.AspNetCore.App" #>
<#@ output extension=".ts" #>
<# /* Environment.CurrentDirectory */ #>

//AUTOGENERATED DO NOT EDIT THIS FILE <#= DateTime.Now.ToString() #>
```
I get 

(0,0): ERROR The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
(0,0): ERROR The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
(0,0): ERROR The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
(0,0): ERROR The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)

**Comment by atifaziz** [comment]
The template engine and language currently has no notion of using NuGet packages, target framework monikers and many things that would be needed to have templates work as smoothly as they did under .NET Framework. Using anything beyond the very basics available in .NET Core is going to be difficult. The right expectation to keep is that T5 will pretty much work (for now) for very simple templates that:

- use C# (i.e. `<#@ template language="C#" #>`)
- don't rely on a specific host (i.e. `<#@ template hostspecific="false"`).
- independent of the IDE (i.e. no `<#@ Assembly name="EnvDTE" #>`).
- don't require external assembly references (i.e. no `@Assembly` directive).

See [my comment](https://github.com/mono/t4/issues/8#issuecomment-363590843) in mono/t4#8 about the goal and scope of T5. If you wish for more complete support so that you have to make the least amount of changes in your templates then [mono/t4](https://github.com/mono/t4) is a better place to ask and look for that as @mhutch has much [more ambitious plans](https://github.com/mono/t4/issues/8#issuecomment-363965310) for T4.

I'm going to close this as out of scope.
